# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('name_store', models.CharField(max_length=255)),
                ('address_store', models.CharField(max_length=255)),
                ('city_store', models.CharField(max_length=255)),
                ('state_store', models.CharField(max_length=255)),
                ('postal_store', models.CharField(max_length=255)),
                ('country_store', models.CharField(max_length=255)),
                ('phone_store', models.IntegerField()),
                ('send_box', models.BooleanField(default=False)),
                ('clabe', models.CharField(max_length=255)),
                ('timestamp', models.DateField(auto_now=True)),
            ],
        ),
    ]
