# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cutflowers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_cutflower', models.CharField(max_length=255)),
                ('name_cutflower', models.CharField(max_length=255)),
                ('weight_cutflower', models.CharField(max_length=255)),
                ('description_cutflower', models.TextField()),
                ('price_cutflower', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pricesend_cutflower', models.DecimalField(decimal_places=2, max_digits=6)),
                ('timestamp', models.DateField(auto_now=True)),
                ('fkstore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cut_flowers', to='stores.Store')),
            ],
        ),
    ]
